[build]
  publish = "."
  functions = "netlify/functions"

# Optional: local dev redirects for clean paths
[[redirects]]
  from = "/"
  to = "/study_guide.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
